"""followers

Revision ID: 006207ba3dce
Revises: 0e128da4c8de
Create Date: 2022-06-02 21:49:48.708973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006207ba3dce'
down_revision = '0e128da4c8de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
